### ISSUE TITLE
Wczytywanie parametrów programu

### ISSUE THREAD

**Issue by piotrchowaniec** [PanDexter/InfixToPostfix-Calculator#1]
Proszę zmienić implementację klasy Main, tak, żeby wyrażenie do zmiany było parametrem wywołania programu, tzn chciałbym móc uruchomić program poleceniem: java Main 3+2
Wynikiem działania tak zmienionego programu powinny być TYLKO 3 linie na wyjściu:
1. wypisane wyrażenie w orginalnej postaci
2. wyrażenie w postaci postfixowej
3. wynik wyrażenia, lub słowo "Błąd" jeśli podano błędne wyrażenie
Przykład:
dla wywołania: java Main 10+2*3 w wyniku otrzymamy:
10+2*3
10 2 3 * +
16

**Comment by PanDexter** [comment]
Zaktualizowałem klasę main dodając funkcjonalność o którą Pan prosił. Przepraszam, że wszystko zajęło tyle czasu ale spodziewałem się powiadomienia od githuba jeśli dostanę Issue do repozytorium. Informację że otrzymałem już zadania dostałem od Pani koleżanki we wtorek po uprzednim moim mailu z zapytaniem o nie, bo w niewiedzy czekałem na maila od Pana.
