### ISSUE TITLE
Przykładowy test jednostkowy

### ISSUE THREAD

**Issue by piotrchowaniec** [PanDexter/InfixToPostfix-Calculator#2]
Proszę dopisać kilka testów jednostkowych do dowolnego fragmentu programu. Można użyć dowolnej biblioteki wspierającej pisanie testów, np. JUnit, TestNG, Spock.

**Comment by PanDexter** [comment]
Dodałem klasę infixToPostfixTest gdzie wykonałem przykładowe 4 testy do programu.
