### ISSUE TITLE
Do zastanowienia

### ISSUE THREAD

**Issue by piotrchowaniec** [PanDexter/InfixToPostfix-Calculator#3]
Proszę się zastanowić jakie zmiany w programie byłyby konieczne, jeśli trzeba by wprowadzić nowy operator arytmetyczny, np potęgowanie zapisywane jako 2^3 (2 do potęgi 3 = 8).

**Comment by PanDexter** [comment]
Trzeba dodać operator w metodzie `isOperator()` z najwyższym priorytetem i dodać działanie podnoszenia do potęgi w metodzie `wynik()`, którą zmieniłem aktualnie na `expressionResult()`. Dodałem te operacje w zaktualizowanej klasie i wszystko działa jak należy.
